from os.path import dirname

sample_file = open(dirname(__file__) + "\\" + "sample.txt", "r")
print(sample_file.read(10))
print(sample_file.tell())
print(sample_file.read(10))
print(sample_file.tell())
print(sample_file.read(10))
print(sample_file.tell())
sample_file.seek(0, 0)
print(sample_file.tell())
print(sample_file.read(10))
print(sample_file.tell())
print(sample_file.read(10))
print(sample_file.tell())
