import os

f = open(os.path.dirname(__file__) + "\\" + "sample.txt", "r")
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())
f.seek(0, 0)
print(f.tell())
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())