f = open("/../Files_Used/sample.txt", "r")
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())
f.seek(0,0)
print(f.tell())
print(f.read(10))
print(f.tell())
print(f.read(10))
print(f.tell())

input("\n\n----------\nHit enter to close\n")